FROM python:3.6-alpine
WORKDIR /opt
RUN apk add --update ca-certificates gcc build-base git postgresql-dev
ENV PYTHONPATH=/opt/
ENV PYTHONUNBUFFERED=1

COPY auth.json /credentials/auth.json
COPY api/requirements.txt requirements.txt
COPY api/requirements-test.txt requirements-test.txt

ARG INCLUDE_TEST=0
RUN REQUERIMENTS_FILE="requirements.txt"; \
    if [ $INCLUDE_TEST == 1 ]; then \
        REQUERIMENTS_FILE="requirements-test.txt"; \
    fi; \
    pip install -r /opt/$REQUERIMENTS_FILE;

